from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import torch
from peft import AutoPeftModelForSequenceClassification
from torch.utils.data import DataLoader
from transformers import AutoFeatureExtractor, AutoTokenizer, DataCollatorWithPadding

try:
    from scripts._bootstrap import project_root
except ModuleNotFoundError:
    from _bootstrap import project_root

PROJECT_ROOT = project_root()

from src.data.audio_datasets import AudioCollator, AudioWaveLMDataset
from src.data.dataset import MSP_Podcast_Dataset
from src.data.precomputed_embeddings_dataset import PrecomputedEmbeddingsDataset
from src.data.text_datasets import TextEncoderDataset
from src.models import load_ccmt_only_model
from src.utils.metrics import compute_classification_metrics
from src.utils.peft_audio import load_peft_audio_classification_model

ID2LABEL = {0: "unsatisfied", 1: "neutral", 2: "satisfied"}


def map_partition(partition: str) -> str:
    normalized = partition.lower()
    if normalized == "test1":
        return "Test1"
    if normalized == "val":
        return "Development"
    if normalized == "train":
        return "Train"
    raise ValueError(f"Unsupported partition: {partition}")


def ensure_exists(path: Path, description: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"{description} not found: {path}")


def infer_modalities_from_checkpoint_name(checkpoint_name: str) -> list[str]:
    tokens = checkpoint_name.split("_")
    modalities: list[str] = []
    index = 0
    while index < len(tokens):
        token = tokens[index]
        if token == "text" and index + 1 < len(tokens):
            candidate = f"text_{tokens[index + 1]}"
            if candidate in {"text_en", "text_es", "text_de", "text_fr"}:
                modalities.append(candidate)
                index += 2
                continue
        if token == "audio":
            modalities.append("audio")
        index += 1

    if modalities:
        return modalities
    return ["text_en", "text_es", "audio"]


def resolve_embeddings_dir_with_test1(primary_dir: Path) -> Path:
    if (primary_dir / "embeddings_test1.pt").exists() and (primary_dir / "metadata_test1.json").exists():
        return primary_dir

    pipeline_root = PROJECT_ROOT / "MSP_Podcast" / "classification_pipeline"
    if not pipeline_root.exists():
        return primary_dir

    run_dirs = [child for child in pipeline_root.iterdir() if child.is_dir()]
    run_dirs.sort(key=lambda item: item.stat().st_mtime, reverse=True)
    for run_dir in run_dirs:
        candidate = run_dir / primary_dir.name
        if (candidate / "embeddings_test1.pt").exists() and (candidate / "metadata_test1.json").exists():
            print(f"[info] using Test1 embeddings fallback: {candidate}")
            return candidate

    return primary_dir


def resolve_text_transcript_for_partition(modality: str, partition: str, default_path: Path) -> Path:
    # for test1 prefer transcripts generated by classification pipeline runs
    if partition.lower() != "test1":
        return default_path

    pipeline_root = PROJECT_ROOT / "MSP_Podcast" / "classification_pipeline"
    if not pipeline_root.exists():
        return default_path

    lang = modality.replace("text_", "")
    transcript_file_name = f"Transcription_{lang}_test1.json"
    run_dirs = [child for child in pipeline_root.iterdir() if child.is_dir()]
    run_dirs.sort(key=lambda item: item.stat().st_mtime, reverse=True)

    for run_dir in run_dirs:
        candidate = run_dir / "transcripts" / transcript_file_name
        if candidate.exists():
            print(f"[info] using Test1 transcript fallback for {modality}: {candidate}")
            return candidate

    return default_path


class SafeAudioDataset(torch.utils.data.Dataset):
    def __init__(self, base_dataset: AudioWaveLMDataset):
        self.base_dataset = base_dataset

    def __len__(self) -> int:
        return len(self.base_dataset)

    def __getitem__(self, idx: int):
        try:
            return self.base_dataset[idx]
        except Exception as exc:
            print(f"[warn] skipping broken audio sample index={idx}: {exc}")
            return None


def safe_audio_collate(batch: list[dict | None]) -> dict[str, torch.Tensor] | None:
    valid_batch = [sample for sample in batch if sample is not None]
    if not valid_batch:
        return None
    return AudioCollator()(valid_batch)


def evaluate_logits_loader(
    loader: DataLoader,
    forward_fn,
    device: str,
    num_labels: int = 3,
    loss_fn: torch.nn.Module | None = None,
) -> dict[str, Any]:
    all_predictions: list[int] = []
    all_labels: list[int] = []
    total_loss = 0.0
    loss_function = loss_fn or torch.nn.CrossEntropyLoss()

    with torch.no_grad():
        for batch in loader:
            if batch is None:
                continue
            labels = batch["labels"].to(device)
            outputs = forward_fn(batch)
            logits = outputs.logits if hasattr(outputs, "logits") else outputs
            logits = logits.float().view(-1, num_labels)
            labels_flat = labels.view(-1)
            total_loss += loss_function(logits, labels_flat).item()
            predictions = logits.argmax(dim=-1)
            all_predictions.extend(predictions.detach().cpu().numpy().tolist())
            all_labels.extend(labels_flat.detach().cpu().numpy().tolist())

    return compute_classification_metrics(
        labels=np.array(all_labels),
        predictions=np.array(all_predictions),
        id2label=ID2LABEL,
        total_loss=total_loss,
        num_batches=len(loader),
    )


def evaluate_text_model(
    checkpoint_dir: Path,
    modality: str,
    transcript_path: Path,
    partition: str,
    batch_size: int,
    device: str,
) -> dict[str, Any]:
    data_dir = PROJECT_ROOT / "MSP_Podcast"
    labels_csv = data_dir / "Labels" / "labels_consensus.csv"
    best_model_path = checkpoint_dir / "best_model"

    ensure_exists(best_model_path, "Text best_model directory")
    ensure_exists(transcript_path, f"Transcript file for {modality}")

    kwargs: dict[str, Any] = {
        "audio_root": str(data_dir / "Audios"),
        "labels_csv": str(labels_csv),
        "partition": partition,
        "modalities": [modality],
    }
    if modality == "text_en":
        kwargs["transcripts_en_json"] = str(transcript_path)
    elif modality == "text_es":
        kwargs["transcripts_es_json"] = str(transcript_path)
    elif modality == "text_de":
        kwargs["transcripts_de_json"] = str(transcript_path)
    elif modality == "text_fr":
        kwargs["transcripts_fr_json"] = str(transcript_path)

    base_dataset = MSP_Podcast_Dataset(**kwargs)
    tokenizer = AutoTokenizer.from_pretrained(best_model_path)
    dataset = TextEncoderDataset(
        base_dataset,
        tokenizer,
        text_fields=[modality],
        max_length=512,
        padding=True,
        sanitize_input_ids=True,
    )
    collator = DataCollatorWithPadding(tokenizer=tokenizer)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, collate_fn=collator)

    model = AutoPeftModelForSequenceClassification.from_pretrained(best_model_path, num_labels=3).to(device)
    model.eval()

    def forward_fn(batch: dict[str, torch.Tensor]):
        token_type_ids = batch.get("token_type_ids")
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        if token_type_ids is None:
            token_type_ids = torch.zeros_like(input_ids, device=device)
        else:
            token_type_ids = token_type_ids.to(device)
        return model(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)

    return evaluate_logits_loader(loader, forward_fn, device)


def evaluate_audio_model(
    checkpoint_dir: Path,
    partition: str,
    batch_size: int,
    device: str,
    kd_profile: bool = False,
) -> dict[str, Any]:
    data_dir = PROJECT_ROOT / "MSP_Podcast"
    labels_csv = data_dir / "Labels" / "labels_consensus.csv"
    best_model_path = checkpoint_dir / "best_model"

    ensure_exists(best_model_path, "Audio best_model directory")

    base_dataset = MSP_Podcast_Dataset(
        audio_root=str(data_dir / "Audios"),
        labels_csv=str(labels_csv),
        partition=partition,
        modalities=["audio"],
    )

    feature_extractor = AutoFeatureExtractor.from_pretrained("microsoft/wavlm-base-plus")
    if kd_profile:
        dataset_kwargs = {
            "max_seconds": 5,
            "do_resample": False,
            "label_key": "label_id",
            "include_attention_mask": True,
            "extractor_padding": False,
            "extractor_truncation": False,
            "extractor_max_length": None,
        }
    else:
        dataset_kwargs = {
            "max_seconds": 5,
            "do_resample": False,
            "label_key": "label_id",
            "include_attention_mask": False,
            "extractor_padding": False,
            "extractor_truncation": False,
            "extractor_max_length": None,
        }

    dataset = AudioWaveLMDataset(base_dataset, feature_extractor, **dataset_kwargs)
    safe_dataset = SafeAudioDataset(dataset)
    loader = DataLoader(safe_dataset, batch_size=batch_size, shuffle=False, collate_fn=safe_audio_collate)
    model = load_peft_audio_classification_model(best_model_path, num_labels=3).to(device)
    model.eval()

    loss_fn = None
    if kd_profile:
        class_weights_dataset = MSP_Podcast_Dataset(
            audio_root=str(data_dir / "Audios"),
            labels_csv=str(labels_csv),
            partition="Train",
            modalities=[],
        )
        all_train_labels = class_weights_dataset.metadata["label_id"].astype(int).to_numpy()
        raw_weights = class_weights_dataset.get_class_weights(all_train_labels, device=device)
        loss_fn = torch.nn.CrossEntropyLoss(weight=torch.sqrt(raw_weights))

    def forward_fn(batch: dict[str, torch.Tensor]):
        return model(
            input_values=batch["input_values"].to(device),
            attention_mask=batch.get("attention_mask").to(device) if batch.get("attention_mask") is not None else None,
        )

    return evaluate_logits_loader(loader, forward_fn, device, loss_fn=loss_fn)


def evaluate_ccmt_model(
    checkpoint_dir: Path,
    embeddings_dir: Path,
    modalities: list[str],
    partition: str,
    batch_size: int,
    device: str,
) -> dict[str, Any]:
    ensure_exists(checkpoint_dir / "best_model.pt", "CCMT best_model.pt")
    embeddings_dir = resolve_embeddings_dir_with_test1(embeddings_dir)
    ensure_exists(embeddings_dir, "CCMT embeddings directory")

    training_config_path = checkpoint_dir / "training_config.json"
    model_config: dict[str, Any] = {}
    if training_config_path.exists():
        with training_config_path.open("r", encoding="utf-8") as handle:
            saved_config = json.load(handle)
        model_config = saved_config.get("model_architecture", {})
    else:
        print(f"[warn] missing training_config.json for {checkpoint_dir.name}, using default CCMT config values")
        if not modalities:
            modalities = infer_modalities_from_checkpoint_name(checkpoint_dir.name)

    dataset = PrecomputedEmbeddingsDataset(
        embeddings_dir=str(embeddings_dir),
        partition=partition.lower(),
        modalities=modalities,
    )
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    model = load_ccmt_only_model(
        device=device,
        text_en_dim=int(model_config.get("text_en_dim", 768)),
        text_es_dim=int(model_config.get("text_es_dim", 768)),
        text_de_dim=int(model_config.get("text_de_dim", 768)),
        text_fr_dim=int(model_config.get("text_fr_dim", 768)),
        audio_dim=int(model_config.get("audio_dim", 768)),
        num_classes=int(model_config.get("num_classes", 3)),
        ccmt_dim=int(model_config.get("ccmt_dim", 768)),
        num_patches_per_modality=int(model_config.get("num_patches_per_modality", 100)),
        ccmt_depth=int(model_config.get("ccmt_depth", 4)),
        ccmt_heads=int(model_config.get("ccmt_heads", 4)),
        ccmt_mlp_dim=int(model_config.get("ccmt_mlp_dim", 1024)),
        ccmt_dropout=float(model_config.get("ccmt_dropout", 0.1)),
        modalities=modalities,
    )
    checkpoint = torch.load(checkpoint_dir / "best_model.pt", map_location=device)
    state_dict = checkpoint["model_state_dict"] if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint else checkpoint
    model.load_state_dict(state_dict, strict=False)
    model = model.to(device)
    model.eval()

    def forward_fn(batch: dict[str, torch.Tensor]):
        inputs = {f"{modality}_emb": batch[f"{modality}_emb"].to(device) for modality in modalities}
        return model(**inputs)

    return evaluate_logits_loader(loader, forward_fn, device)


def save_results(output_dir: Path, results: dict[str, Any]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    with (output_dir / "test_results.json").open("w", encoding="utf-8") as handle:
        json.dump(results, handle, indent=2)


def main() -> None:
    parser = argparse.ArgumentParser(description="Test suite for classification models on Test1")
    parser.add_argument("--partition", type=str, default="test1", choices=["test1", "val", "train"])
    parser.add_argument("--output-root", type=Path, default=PROJECT_ROOT / "results" / "classification_test1_suite")
    parser.add_argument("--text-batch-size", type=int, default=32)
    parser.add_argument("--audio-batch-size", type=int, default=8)
    parser.add_argument("--ccmt-batch-size", type=int, default=32)
    args = parser.parse_args()

    partition = map_partition(args.partition)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    data_dir = PROJECT_ROOT / "MSP_Podcast"
    transcript_paths = {
        "text_en": data_dir / "Transcription_en.json",
        "text_es": data_dir / "Transcription_es.json",
        "text_de": data_dir / "Transcription_de.json",
        "text_fr": data_dir / "Transcription_fr.json",
    }

    model_specs: list[dict[str, Any]] = [
        {
            "name": "wavlm_audio",
            "kind": "audio",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "wavlm_audio",
            "kd_profile": False,
        },
        {
            "name": "roberta_text_en",
            "kind": "text",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "roberta_text_en",
            "modality": "text_en",
        },
        {
            "name": "roberta_text_es",
            "kind": "text",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "roberta_text_es",
            "modality": "text_es",
        },
        {
            "name": "roberta_text_de",
            "kind": "text",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "roberta_text_de",
            "modality": "text_de",
        },
        {
            "name": "roberta_text_fr",
            "kind": "text",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "roberta_text_fr",
            "modality": "text_fr",
        },
        {
            "name": "ccmt_multimodal_text_en_audio",
            "kind": "ccmt",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "ccmt_multimodal_text_en_audio",
            "embeddings_dir": PROJECT_ROOT / "MSP_Podcast" / "embeddings_text_en_audio",
            "modalities": ["text_en", "audio"],
        },
        {
            "name": "ccmt_multimodal_text_en_text_es_audio",
            "kind": "ccmt",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "ccmt_multimodal_text_en_text_es_audio",
            "embeddings_dir": PROJECT_ROOT / "MSP_Podcast" / "embeddings",
            "modalities": ["text_en", "text_es", "audio"],
        },
        {
            "name": "ccmt_multimodal_text_en_text_de_audio",
            "kind": "ccmt",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "ccmt_multimodal_text_en_text_de_audio",
            "embeddings_dir": PROJECT_ROOT / "MSP_Podcast" / "embeddings_text_en_text_de_audio",
            "modalities": ["text_en", "text_de", "audio"],
        },
        {
            "name": "ccmt_multimodal_text_en_text_fr_audio",
            "kind": "ccmt",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "ccmt_multimodal_text_en_text_fr_audio",
            "embeddings_dir": PROJECT_ROOT / "MSP_Podcast" / "embeddings_text_en_text_fr_audio",
            "modalities": ["text_en", "text_fr", "audio"],
        },
        {
            "name": "ccmt_multimodal_text_en_text_es_text_de_text_fr_audio",
            "kind": "ccmt",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "ccmt_multimodal_text_en_text_es_text_de_text_fr_audio",
            "embeddings_dir": PROJECT_ROOT / "MSP_Podcast" / "embeddings_text_en_text_es_text_de_text_fr_audio",
            "modalities": ["text_en", "text_es", "text_de", "text_fr", "audio"],
        },
        {
            "name": "wavlm_audio_kd_text_en_text_fr_audio_retrained_teacher",
            "kind": "audio",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "wavlm_audio_kd_text_en_text_fr_audio_retrained_teacher",
            "kd_profile": True,
        },
        {
            "name": "wavlm_audio_kd_text_en_text_de_audio",
            "kind": "audio",
            "checkpoint_dir": PROJECT_ROOT / "checkpoints" / "wavlm_audio_kd_text_en_text_de_audio",
            "kd_profile": True,
        },
    ]

    summary: dict[str, Any] = {
        "partition": args.partition,
        "device": device,
        "models": {},
        "failures": {},
    }

    for spec in model_specs:
        model_name = spec["name"]
        print(f"\nEvaluating {model_name}...")
        try:
            if spec["kind"] == "text":
                modality = spec["modality"]
                transcript_path = resolve_text_transcript_for_partition(
                    modality=modality,
                    partition=args.partition,
                    default_path=transcript_paths[modality],
                )
                results = evaluate_text_model(
                    checkpoint_dir=spec["checkpoint_dir"],
                    modality=modality,
                    transcript_path=transcript_path,
                    partition=partition,
                    batch_size=args.text_batch_size,
                    device=device,
                )
            elif spec["kind"] == "audio":
                results = evaluate_audio_model(
                    checkpoint_dir=spec["checkpoint_dir"],
                    partition=partition,
                    batch_size=args.audio_batch_size,
                    device=device,
                    kd_profile=bool(spec.get("kd_profile", False)),
                )
            elif spec["kind"] == "ccmt":
                results = evaluate_ccmt_model(
                    checkpoint_dir=spec["checkpoint_dir"],
                    embeddings_dir=spec["embeddings_dir"],
                    modalities=spec["modalities"],
                    partition=args.partition,
                    batch_size=args.ccmt_batch_size,
                    device=device,
                )
            else:
                raise ValueError(f"Unknown model kind: {spec['kind']}")

            output_dir = args.output_root / model_name
            save_results(output_dir, {k: v for k, v in results.items() if k not in ["predictions", "labels"]})
            summary["models"][model_name] = {
                "accuracy": float(results["accuracy"]),
                "f1_macro": float(results["f1_macro"]),
                "f1_weighted": float(results["f1_weighted"]),
                "precision_macro": float(results["precision_macro"]),
                "recall_macro": float(results["recall_macro"]),
                "avg_loss": float(results["avg_loss"]),
                "num_samples": int(results["num_samples"]),
            }
            print(
                f"[OK] {model_name}: "
                f"acc={results['accuracy']:.4f}, f1_macro={results['f1_macro']:.4f}, loss={results['avg_loss']:.4f}"
            )
        except Exception as exc:
            summary["failures"][model_name] = str(exc)
            print(f"[FAIL] {model_name}: {exc}")

    args.output_root.mkdir(parents=True, exist_ok=True)
    with (args.output_root / "summary.json").open("w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2)

    print("\nDone.")
    print(f"Summary saved to: {args.output_root / 'summary.json'}")


if __name__ == "__main__":
    main()
